"""Build a searchable seed supplier resource from source-reviewed records."""
import json,html
from pathlib import Path
from directory_brand import brand_page
from directory_data import script_json
ROOT=Path(__file__).resolve().parent
OUT=ROOT/'seeds.html'
def main():
 rows=json.loads((ROOT/'seed-suppliers.json').read_text())
 def esc(s):return html.escape(str(s),quote=True)
 cards=[]
 for i,r in enumerate(rows):
  sources=' · '.join(f'<a href="{esc(u)}">Source {j+1}</a>' for j,u in enumerate(r['sources']))
  contact=(f'<a href="tel:{r["phone"]}">Call {r["phone"]}</a> ' if r['phone'] else '')+(f'<a href="mailto:{esc(r["email"])}">Email</a>' if r['email'] else '')
  cards.append(f'<article data-index="{i}" id="supplier-{i+1}"><h2><a href="{esc(r["url"])}">{esc(r["name"])}</a></h2><p class="meta">{esc(r["area"])} · {esc(r["role"])} · {esc(", ".join(r["types"]) or "Seed types not independently reviewed")}</p><p>{esc(r["note"])}</p><p><strong>Shipping / pickup:</strong> {esc(r["shipping"])}</p><p>{contact}</p><details><summary>Evidence reviewed {esc(r["reviewed"])}</summary><p>{sources}</p></details></article>')
 types=sorted({t for r in rows for t in r['types']})
 page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Seed Suppliers Serving Ohio | VHG Cannabis Directory</title><meta name="description" content="Compare seed breeders, seed banks and local grow suppliers: Ohio connections, seed types, shipping evidence and pickup details."><style>
 :root{--ink-soft:#555;--field-deep:#9d0927}*{box-sizing:border-box}body{margin:0;background:#faf9f6;color:#25282b;font:16px/1.6 system-ui,sans-serif}.wrap{max-width:960px;margin:auto;padding:28px 20px}a{color:var(--field-deep);overflow-wrap:anywhere}a:focus-visible,input:focus-visible,select:focus-visible,button:focus-visible{outline:3px solid #9d0927;outline-offset:3px}h1{font-size:clamp(1.7rem,5vw,2.5rem);line-height:1.2}h2{font-size:1.18rem;line-height:1.35}p{max-width:80ch}.controls{display:flex;gap:10px;flex-wrap:wrap}label{display:block}input,select,button{font:inherit;padding:8px;border:1px solid #aaa;background:white;max-width:100%}.controls>label:first-child{flex:1 1 260px}.controls input{width:100%}article{padding:18px 0;border-top:1px solid #ccc;overflow-wrap:anywhere}article p{margin:8px 0}.meta,details,footer{font-size:.88rem;color:#555}.guide{border-left:4px solid #ba0c2f;padding:4px 16px;background:white;margin:24px 0}footer{border-top:1px solid #ccc;padding-top:20px;margin-top:20px}[hidden]{display:none!important}__VHG_CSS__@media print{.controls{display:none}article{break-inside:avoid}body{background:white}}
 </style></head><body><main class="wrap">__VHG_BRAND__<p><a href="resources.html#seeds">← Consumer resources</a> · <a href="index.html">Full organization directory</a></p><h1>Find seeds and local growing supplies</h1><p>__COUNT__ source-reviewed supplier entries: __SEED_COUNT__ seed providers and one Ohio grow-supply / retailer lead. Compare what is verified before ordering or traveling.</p><div class="guide"><p><strong>Two different questions:</strong> feminized vs. regular describes expected plant sex; autoflower vs. photoperiod describes flowering behavior. A seed can be both feminized and autoflower. Filters reflect reviewed catalogs, not live stock.</p><p>Ohio connections appear first. Supplier shipping statements do not establish legal eligibility. Current Ohio seed pickup is not confirmed for any listed Ohio seller; the Michigan storefront is labeled separately. <a href="resources.html#rules">Read Ohio rules</a>.</p></div><div class="controls"><label>Search supplier, city or detail<input id="seed-q" type="search" placeholder="Columbus, autoflower, Michigan…"></label><label>Location<select id="seed-area"><option value="">All locations</option><option>Ohio</option><option>Michigan</option><option>National</option></select></label><label>Seed type<select id="seed-type"><option value="">All reviewed types</option>__TYPES__</select></label><button id="seed-reset" type="button">Reset</button></div><p id="seed-tally" role="status" aria-live="polite">__COUNT__ entries</p><div id="seed-results">__CARDS__</div><p id="seed-empty" hidden>No matching reviewed suppliers. Reset the filters or report a missing supplier below.</p><noscript><p>All suppliers are shown. Search and filters need JavaScript.</p></noscript><footer><p>Reviewed October 9, 2026. No paid placements or quality rankings. Retailer inventory, pricing, Ohio shipping eligibility and local seed pickup need direct confirmation. No licensed Ohio dispensary seed/clone stock has been verified in this list.</p><p>Source data: <a href="seed-suppliers.json" download>Download supplier data</a>. Maintained by Travis Vought for Veteran Home Guardians. <a href="__UPDATE_URL__">Suggest a supplier or correction</a>: __VHG_EMAIL__.</p></footer></main><script>
 const suppliers=__DATA__;const q=document.getElementById('seed-q'),area=document.getElementById('seed-area'),type=document.getElementById('seed-type');
 function renderSeeds(){const terms=q.value.toLowerCase().trim().split(/\\s+/).filter(Boolean);let count=0;document.querySelectorAll('#seed-results article').forEach(card=>{const r=suppliers[Number(card.dataset.index)];const hay=[r.name,r.area,r.role,r.note,r.shipping,...r.types].join(' ').toLowerCase();const visible=(!area.value||r.area===area.value)&&(!type.value||r.types.includes(type.value))&&terms.every(t=>hay.includes(t));card.hidden=!visible;if(visible)count++;});document.getElementById('seed-tally').textContent=count+' of '+suppliers.length+' entries';document.getElementById('seed-empty').hidden=count!==0;const params=new URLSearchParams();if(q.value)params.set('q',q.value);if(area.value)params.set('area',area.value);if(type.value)params.set('type',type.value);history.replaceState(null,'',location.pathname+(params.size?'?'+params:'')+location.hash);}
 function loadSeeds(){const p=new URLSearchParams(location.search);q.value=p.get('q')||'';area.value=p.get('area')||'';type.value=p.get('type')||'';renderSeeds();}
 q.addEventListener('input',renderSeeds);area.addEventListener('change',renderSeeds);type.addEventListener('change',renderSeeds);document.getElementById('seed-reset').addEventListener('click',()=>{q.value='';area.value='';type.value='';renderSeeds();});window.addEventListener('popstate',loadSeeds);loadSeeds();
 </script></body></html>'''
 page=page.replace('__COUNT__',str(len(rows))).replace('__SEED_COUNT__',str(len(rows)-1)).replace('__TYPES__',''.join(f'<option>{esc(t)}</option>' for t in types)).replace('__CARDS__',''.join(cards)).replace('__DATA__',script_json(rows))
 OUT.write_text(brand_page(page),encoding='utf-8');print(f'Built seeds.html: {len(rows)} entries')
if __name__=='__main__':main()
